### ISSUE TITLE
code blocks are getting streched a log

### ISSUE THREAD

**Issue by prishs** [arashsm79/hugo-PaperMod-Mod#2]
Hello,

  while looking for solution to have ToC, i came across this repo.. 

  I included all the files included in this repo to assets/css/extended. but it is not getting applied properly. code blogs are getting stretched beyond normal screens if I add sidetoc.css

 what could I be doing wrong?

**Comment by arashsm79** [comment]
Thanks!
I think [this commit](https://github.com/arashsm79/hugo-PaperMod-Mod/commit/edf45432dfb0b72ff9b66302e748d4f93e320b3d) fixes this issue.
